version: '3.8'
services:
  backend_java_citcd:
    container_name: java_app_citcd
    image: backend/java:1.0.0
    build:
      context: .
    ports:
      - "8082:8090"
    networks:
      - backend_citcd
    restart: always

networks:
  backend_citcd:
    name: backend_citcd
